name: Publish

on:
  release:
    types: [released]

jobs:
  verify:
    name: Verify tag
    runs-on: ubuntu-latest

    outputs:
      valid: ${{ steps.check-tag.outputs.valid }}

    steps:
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "valid=true" >> $GITHUB_OUTPUT
          fi

  publish:
    if: needs.verify.outputs.valid == 'true'
    name: Release
    runs-on: ubuntu-latest
    needs: verify

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Get meta
        id: meta
        run: |
          TAG=$(echo $GITHUB_REF | cut -d / -f 3)
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT
          VCS_REF=$(echo $GITHUB_SHA)
          echo "vcs_ref=${VCS_REF}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_UPLOAD_PACKAGES }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ steps.meta.outputs.tag }}
            BUILD_DATE=${{ steps.meta.outputs.build_date }}
            COMMIT=${{ steps.meta.outputs.vcs_ref }}
          tags: |
            ghcr.io/caido/kratos:latest
            ghcr.io/caido/kratos:${{ steps.meta.outputs.tag }}
